//
// Created by Sigve Røkenes on 25/10/2018.
//


#define TILE_SIZE 80

#define PACKET_TYPE_LOBBY 0
#define PACKET_TYPE_START 1
#define PACKET_TYPE_WORLD 2
#define PACKET_TYPE_PIECE 3
#define PACKET_TYPE_BLOCK 4
#define PACKET_TYPE_GAMEOVER 5
#define PACKET_TYPE_FINISHGAME 6